name: flutter_kakao_profile_d5354
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# image_picker : 촬영한 사진이나 갤러리의 이미지 가져오기
# image_picker : 이미지 자르기
# get : GetX. 상태관리 및 기타 다양한 기능을 제공함.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  get: ^4.6.6
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_storage: ^11.5.3
  cloud_firestore: ^4.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
